### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by cpaulik** [TUW-GEO/ismn#14]
Could we make a new release? 

The[ `allow_pickle` issue](https://github.com/TUW-GEO/ismn/issues/10) is now also influencing the pytesmo tests.

**Comment by cpaulik** [comment]
@wpreimes I got an email but Github that v0.3.1 was released but now I can't find it anymore?

**Comment by wpreimes** [comment]
Yes, I had to revert it because of a python 2 issue that we should fix first. Anyway I will try to upload the new release to pypi today.

**Comment by cpaulik** [comment]
Great, Thanks.

**Comment by wpreimes** [comment]
It's released now
