### ISSUE TITLE
read from zip file

### ISSUE THREAD

**Issue by wpreimes** [TUW-GEO/ismn#22]
Would be nice if (optional) reading data from the downloaded zip file directly was possible (would be slower of course) with this package. It would save a lot of storage space. Could someone of you have a look at this, I guess there should be python libraries for that?

**Comment by sebhahn** [comment]
I think this is not possible, at least at the time I was searching for this. I ended up unzipping the required file into a temporary location (on linux /tmp) and reading this one. E.g. this is still the case for reading L1b ASCAT data.

**Comment by cpaulik** [comment]
What should be possible is to get the file list from the zip file and build the metadata database from that. After this it would indeed be possible to extract the specific file to tmp and read it.

**Comment by wpreimes** [comment]
This is included after `v1.0`
