### ISSUE TITLE
setuptools_scm conflicts with other environments

### ISSUE THREAD

**Issue by teije01** [TUW-GEO/ismn#36]
since the latest release of 1.0, [setuptools_scm is a package requirement](https://github.com/TUW-GEO/ismn/commit/4ff6fab5d5ef1b44a4bf5fe2c01694d35b598573#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R40). 

However, it would be nice if that can be changed to a build_dependency since it is not required for running the package itself (or is it?)

For environments that used an (outdated) version of pyscaffold, the installation of `setuptools_scm` results in a failed installation.
```
    AttributeError: module 'setuptools_scm.git' has no attribute 'list_files_in_archive'
```

**Comment by wpreimes** [comment]
I think we dont need setuptools_scm in dependecies for ismn @daberer 
We will release a patch for this and some other issues soon
