### ISSUE TITLE
'ISMN_Interface' object has no attribute 'collection'

### ISSUE THREAD

**Issue by xushanthu-2014** [TUW-GEO/ismn#46]
To whom it may concern
I downloaded ISMN data (network = ORACLE) in northern France and got two files: ```Data_separate_files_19801023_20211011_9078_f2h4_20211012.zip``` and ```Data_separate_files_header_19801023_20211011_9078_dRV2_20211012.zip```. And I used following codes to read them:
```
from ismn.interface import ISMN_Interface
import numpy as np
import matplotlib.pyplot as plt  # matplotlib is not installed automatically
%matplotlib inline

# Either a .zip file or one folder that contains all networks, here we read from .zip
data_path = "/Users/xushan/research/TUD/ISMN/Data_separate_files_header_19801023_20211011_9078_dRV2_20211012"
ismn_data = ISMN_Interface(data_path)

ismn_data.collection #  or just:  ismn_data  - overview over loaded networks and their stations

```
But I got an error like: ```AttributeError: 'ISMN_Interface' object has no attribute 'collection'```. Could you please help me with this? And the version is ```'0.3.2'```.

**Comment by wpreimes** [comment]
Hi @xushanthu-2014. The documentation refers to the latest version of the package (i.e. `>1.0`). As you are using an older version of the package - which works a bit differently - please look at the docs from that version on how to use the library: https://ismn.readthedocs.io/en/v0.4/
