### ISSUE TITLE
how to use "ISMN_interface serveral" to load data from several download zip files? 

### ISSUE THREAD

**Issue by pipipercy** [TUW-GEO/ismn#48]
Hi

I download the ISMN data from different networks. The data are downloaded in separately several zip files. I want to load these zip files once and plot different networks in one figure use `ismn_data.plot_station_locations`. Is there any solution?

Thanks for your kind support.

**Comment by wpreimes** [comment]
Hi, it should be possible - as long as you don't have any duplicate networks - to extract the network folders from your zip files, put them into a new folder and give that folder to the `ISMN_Interface` class as input. Make sure to structure the extracted networks like this, and to delete any old `python_metadata` folders you might have:
```
Your_merged_networks/
├── network/
│   ├── station/
│   │   ├── sensor.stm
│   │   ├── sensor.stm
│   │   ├── ...
│   │   ├── sensor.stm
│   │   ├── static_variables.csv
│   ├── station/
│   │   ├── ...
├── network/
│   ├── ...
```

**Comment by pipipercy** [comment]
Thanks for your kind help.
