### ISSUE TITLE
no 'display' is found in 'docs/examples/interface.ipynb'

### ISSUE THREAD

**Issue by pipipercy** [TUW-GEO/ismn#49]
Hi,
I am trying to implement some scripts in `docs/examples/interface.ipynb`.
However, when it comes to the lines - `display(network)`. The error occurs - **undefined**.
I check the whole text and do not find the relevant definition.
Could you help me figure it out?

**Comment by wpreimes** [comment]
`display` is an IPython function. See here https://stackoverflow.com/a/49328495
If you are not working in an ipython environment (the example runs in a jupyter notebook) the command might not work, and you might want to replace it with `print()` or just skip these lines.
