### ISSUE TITLE
"orig_flag" in "ts" via "ismn_data.read"

### ISSUE THREAD

**Issue by pipipercy** [TUW-GEO/ismn#50]
Hi,
Here are my code to read data
```python
ids = ismn_data.get_dataset_ids(variable='soil_moisture', 
                                max_depth=1)


ts, meta = ismn_data.read(ids[0], return_meta=True)
ts
```
after running it, i get
``` shell
                     soil_moisture soil_moisture_flag soil_moisture_orig_flag
date_time                                                                    
2015-01-01 00:00:00         0.2608                D03                       M
2015-01-01 01:00:00         0.2607                D03                       M
2015-01-01 02:00:00         0.2606                D03                       M
2015-01-01 03:00:00         0.2605                D03                       M
```
I found the mean of `soil_moisture_flag` in [here](https://github.com/TUW-GEO/flagit/blob/master/README.rst), but fail to find the mean of `soil_moisture_orig_flag`. what does the `M` denotes?
Could you please help explain it for me?

**Comment by daberer** [comment]
Hi pipipercy. 

the "M" (missing) in the orig_flag column means that the data provider did not supply own quality flags. You can ignore that. See here for a short description of the quality flags -> [https://ismn.earth/en/data/ismn-quality-flags/](https://ismn.earth/en/data/ismn-quality-flags/). If you want to know a little more of the background of the quality flags you can check out [https://hess.copernicus.org/articles/25/5749/2021/hess-25-5749-2021.pdf](https://hess.copernicus.org/articles/25/5749/2021/hess-25-5749-2021.pdf). 
Hope this helps!

PS: When you download data at the ISMN there is also a txt file included called ISMN_qualityflags_description.txt that gives a short description, and we have a github repo dedicated to the soil moisture quality flagging [https://github.com/TUW-GEO/flagit](https://github.com/TUW-GEO/flagit).
