### ISSUE TITLE
file read error because of csv formatting issue

### ISSUE THREAD

**Issue by ypwong22** [TUW-GEO/ismn#69]
The package gives an error when it tries to read a file in the RISMA network, CEF station

file: ``RISMA_RISMA_CEF_sm_0.050000_0.050000_Hydraprobe-II-Sdi-12-A_20000101_20230605.stm

error: ParserError: Error tokenizing data. C error: Expected 9 fields in line 5316, saw 10

The error seems to be generated by pd.read_csv in filehander.py > __read_format_header_values > __read_csv when it tries to access the line

2015/12/01 06:00 0.06 D01,D02,D03 OK,OK,NA,NA,Out of WFV average range,Frozen soil

**Comment by wpreimes** [comment]
Thanks, this was recently fixed in #67 but not yet released. I will release v1.3.4 to include the fix in the pypi package

**Comment by wpreimes** [comment]
I have just released the new version. I downloaded the CEF station data from ISMN and could read the time series data. But if there are still issues for you, just let me know.
