### ISSUE TITLE
The unit of the variable.

### ISSUE THREAD

**Issue by lizhuoq** [TUW-GEO/ismn#78]
I couldn't find your description about the units. Can I understand the unit of soil moisture as m3/m3, the units of soil temperature, air temperature, and soil surface temperature as °C, the unit of precipitation as mm/h, the unit of soil suction as kPa, and the units of snow water equivalent and snow depth as mm? With respect for your work, I hope to receive your reply. Thank you.

**Comment by wpreimes** [comment]
Hi @lizhuoq. Thanks for bringing this up. Yes these are the correct units. Still, I think you have a valid point that it is not immediately clear what the correct units for each variable are from the website and downloaded data.
I have notified the ISMN maintainers about providing the units more clearly and I will keep this issue open as a reminder for myself to integrate them better in this package as well.

**Comment by lizhuoq** [comment]
@wpreimes Thank you for your reply, thank you for your efforts, it's very helpful to me. Best wishes!
