### ISSUE TITLE
Regarding issues and suggestions about metadata.

### ISSUE THREAD

**Issue by lizhuoq** [TUW-GEO/ismn#80]
First of all, thank you for your dedication to this project, which has been very helpful to me. However, I am not clear about the units of continuous variables in the metadata, such as `clay_fraction, organic_carbon, and sand_fraction`. I cannot intuitively obtain the units of these variables. Could you please provide me with the units of these variables in the metadata? Similar to the [issue](https://github.com/TUW-GEO/ismn/issues/78) I mentioned earlier, I believe it is crucial to intuitively obtain the units of different variables, and this needs to be addressed urgently.

Therefore, I have a suggestion to address this issue. It would be helpful to add a function `def get_unit() -> dict[str, str]`, which would directly return all the variables related to ISMN along with their units. This information could be stored as a JSON file, and when users call get_unit(), it would return a dictionary directly. I suggest using LaTeX formatting for the units.

I hope to receive your response soon. Thank you.

**Comment by wpreimes** [comment]
They are all expressed as a percentage value (% weight). Sand / Clay / silt fraction should add up to 100% and are taken from the [Harmonized World Soil Database.](http://webarchive.iiasa.ac.at/Research/LUC/External-World-soil-database/HTML/)
![image](https://github.com/TUW-GEO/ismn/assets/24410143/57ad2ef2-f8f8-4b1d-8d9e-ce05d4b1d13b)

**Comment by lizhuoq** [comment]
Thank you for your response, it's really timely. Please forgive my lack of knowledge in soil texture.

**Comment by wpreimes** [comment]
No problem, please also see **Table 2** in the following article https://doi.org/10.5194/hess-25-5749-2021

**Comment by lizhuoq** [comment]
@wpreimes Thank you for your nice reply, it's very helpful to me! Wish you all the best!
